apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-node
spec:
  clusterIP: None
  ports:
  - name: amqp
    port: 5672
  - name: http
    port: 15672
  publishNotReadyAddresses: true
  selector:
    service: rabbitmq
