apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager-flask-log
  name: alertmanager-flask-log
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
  selector:
    app: alertmanager-flask-log
  type: ClusterIP