kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  labels:
    app: redis
data:
  redis.conf: |-
    dir /data
    port 6379
    timeout 100
    bind 0.0.0.0
    appendonly yes
    protected-mode no
    requirepass gp51redis@prod
    pidfile /tmp/redis-6379.pid