namespace: common
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SPRING_PROFILES_INCLUDE
        value: prod
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 4G
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 2G
  target:
    kind: Deployment
    name: cas-server
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: common/cas-server
  newTag: 1.7.0
