apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk-0
  labels:
    type: local
spec:
  storageClassName: zk
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/k8sdata/zookeeper/zk-0"
