filebeat.inputs:
  - type: container
    paths:
      - /var/log/containers/*.log
    fields:
      service: k8s-log
    multiline:
      match: after
      negate: true
      pattern: ^\[tx
    processors:
      - add_kubernetes_metadata:
          default_indexers.enabled: true
          default_matchers.enabled: true
          host: ${NODE_NAME}
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/"
      - drop_fields:
          fields: ["host", "tags", "ecs", "log", "prospector", "agent", "input", "beat", "offset"]
          ignore_missing: true
#output.elasticsearch:
#  hosts: ['${ELASTICSEARCH_HOST:10.90.71.93}:${ELASTICSEARCH_PORT:9200}']
output.logstash:
  hosts: ["graylog3.default:5044"]
