apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-nacos
  labels:
    app: mysql-nacos
data:
  server.cnf: |
    # Apply this config only on the master.
    [mysqld]
    innodb_buffer_pool_size = 512M
    innodb_log_file_size    = 256M
    innodb_log_files_in_group = 4
    innodb_data_file_path = ibdata1:100M:autoextend
    innodb_large_prefix = 1
    innodb_file_per_table = 1
    innodb_flush_log_at_trx_commit = 0
    innodb_file_format  = BARRACUDA
    innodb_temp_data_file_path=ibtmp1:20M:autoextend:max:500M
    innodb_change_buffering=all
    default-storage-engine = InnoDB
    sort_buffer_size = 16M
    server-id        = 10
    log-bin          = mysql-bin
    binlog_format    = row
    max_connect_errors = 1000
    max_connections = 1024
    character-set-server = utf8
    collation-server     = utf8_unicode_ci
    table_open_cache = 16384
    expire_logs_days = 5
    lower_case_table_names = 1
    connect_timeout = 60
    [mysqld_safe]
    open-files-limit = 8192