kind: Service
apiVersion: v1
metadata:
  name: mysql-nacos     
  labels:
    app: mysql-nacos          
spec:
  ports:
  - name: mysql-nacos
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql-nacos
