apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  project: minio
  source:
    path: minio/minio/overlays/test
    repoURL: https://github.com/wgzhao/k8s-deployment.git
    targetRevision: HEAD
  syncPolicy: {}