apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-sso-test
  namespace: argocd
spec:
  destination:
    namespace: sso-test
    server: https://kubernetes.default.svc
  project: sso
  source:
    path: sso/ingress-sso/overlays/test
    repoURL: https://github.com/wgzhao/k8s-deployment.git
    targetRevision: HEAD
  syncPolicy: {}