apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash/logstash:7.16.3
        env:
          - name: ELASTICSEARCH_URL
            value: http://es-cluster:9200 # The domain es-cluster will resolve to a list of IP addresses for the 3 Elasticsearch Pods. 
          - name: LS_JAVA_OPTS
            value: "-Xmx1800m -Xms1800m"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            memory: "2Gi"
        ports:
        - containerPort: 5601
        volumeMounts:
          - name: logstash-cfg
            mountPath: /usr/share/logstash/pipeline/
            readOnly: true
          - name: logstash-yml
            mountPath: /usr/share/logstash/config/
            readOnly: true
      volumes:
        - name: logstash-cfg
          hostPath:
            path: /data/k8sdata/elk/logstash/pipeline
        - name: logstash-yml
          hostPath:
            path: /data/k8sdata/elk/logstash/config
