apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk
  labels:
    app: logstash
spec:
  ports:
  - name: listen
    port: 5044
  - name: port2
    port: 5000
  - name: port3
    port: 9600
  selector:
    app: logstash