apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm                           
data:
  mysql.service.name: "mysql-nacos.nacos"        
  mysql.db.name: "nacos_config"            
  mysql.port: "3306"                    
  mysql.user: "nacos"                  
  mysql.password: "9P5V1n3LQC3p"  