apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-iq-server
  name: nexus-iq-server
spec:
  ports:
  - name: web-ui
    port: 8070
    protocol: TCP
  - name: admin-port
    port: 8071
    protocol: TCP
  selector:
    app: nexus-iq-server
  type: ClusterIP