apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pmm-server
  name: pmm
spec:
  selector:
    matchLabels:
      app: pmm-server
  template:
    metadata:
      labels:
        app: pmm-server
    spec:
      containers:
      - name: pmm
        image: percona/pmm-server:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
            cpu: "200m"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pmm-client
  name: pmm-client
spec:
  selector:
    matchLabels:
      app: pmm-client
  template:
    metadata:
      labels:
        app: pmm-client
    spec:
      containers:
      - name: pmm-client
        image: percona/pmm-client:2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "1Gi"
            cpu: "200m"
        env:
          - name: PMM_AGENT_SERVER_ADDRESS
            value: pmm-server-internal:443
          - name: PMM_AGENT_SERVER_USERNAME
            value: admin
          - name: PMM_AGENT_SERVER_PASSWORD
            value: Nyrzon-1mysra-hentov
          - name: PMM_AGENT_SERVER_INSECURE_TLS
            value: "1"
          - name: PMM_AGENT_SETUP
            value: "1"
          - name: PMM_AGENT_CONFIG_FILE
            value: config/pmm-agent.yaml
      restartPolicy: Always