apiVersion: v1
kind: Service
metadata:
  labels:
    app: pmm-server
  name: pmm-server
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 50080
    protocol: TCP
  selector:
    app: pmm-server
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pmm-server
  name: pmm-server-internal
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: pmm-server
  type: ClusterIP
  