namespace: grp-arch
resources:
- ../../base
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: SMS_URL
        value: http://10.90.23.32:9090/sms/api/v1/smsSender
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ENV
        value: prod
  target:
    kind: Deployment
    name: alertmanager-flask-log

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: grp-arch/alertmanager-flask
  newTag: 1.10.0
