apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ZOO_SERVERS
          value:
            zookeeper-0.zookeeper-headless.zookeeper.svc.cluster.local:2888:3888::1
            zookeeper-1.zookeeper-headless.zookeeper.svc.cluster.local:2888:3888::2
            zookeeper-2.zookeeper-headless.zookeeper.svc.cluster.local:2888:3888::3
    target:
      kind: StatefulSet
      name: zookeeper
