apiVersion: v2
appVersion: v1.44.0
description: Prometheus exporter for Redis metrics
name: exporter
version: 5.3.0
home: https://github.com/oliver006/redis_exporter
sources:
  - https://github.com/oliver006/redis_exporter
keywords:
  - prometheus
  - redis
maintainers:
  - name: acondrat
    email: arcadie.condrat@gmail.com
  - name: zanhsieh
    email: zanhsieh@gmail.com
type: application
