apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cloopy
  name: cloopy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloopy
  template:
    metadata:
      labels:
        app: cloopy
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      dnsConfig:
        options:
        - name: ndots
          value: "5"
      containers:
      - image: library/cloopy:latest
        name: cloopy
        imagePullPolicy: Always
        ports:
        - name: service-port
          containerPort: 12345
        startupProbe:
          tcpSocket:
            port: service-port
          failureThreshold: 20
          periodSeconds: 5
          initialDelaySeconds: 20
        readinessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 15
          periodSeconds: 3
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            memory: "256Mi"
        env:
          - name: TZ
            value: Asia/Chongqing