apiVersion: v1
kind: Service
metadata:
  name: kafka-cs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9092
      name: server
      targetPort: 9092
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0
spec:
  ports:
  - port: 9092
    name: client
    targetPort: 9092
    nodePort: 13092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  ports:
  - port: 9092
    name: client
    targetPort: 9092
    nodePort: 13093
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2
spec:
  ports:
  - port: 9092
    name: client
    targetPort: 9092
    nodePort: 13094
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
  type: NodePort