apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: bitnami/kafka:3.2
        ports:
        - containerPort: 9092
          name: client3
        - containerPort: 1099
          name: jmx3
        command:
          - bash
          - -ec
          - |
            HOSTNAME=`hostname -s`
            if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
              ORD=${BASH_REMATCH[2]}
              PORT=$((ORD + 9092))
              export KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://10.90.23.32:$PORT"
            else
              echo "Failed to get index from hostname $HOST"
              exit 1
            fi
            /opt/bitnami/scripts/kafka/run.sh --override zookeeper.connect=zk-cs.default:2181 --override broker.id=${ORD}
        env:
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"
          - name: KAFKA_ZOOKEEPER_PROTOCOL
            value: PLAINTEXT
          - name: KAFKA_CFG_ZOOKEEPER_CONNECT
            value: "zk-cs.default:2181"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zk-cs.default:2181"
          - name: KAFKA_HEAP_OPTS
            value: "-Xmx1024m -Xms1024m"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: kafkadata
            mountPath: /bitnami/kafka
            subPathExpr: $(POD_NAME)
      volumes:
        - name: kafkadata
          hostPath:
            path: /opt/data/kafka



            
