apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamsets
  name: streamsets
spec:
  ports:
  - name: http
    port: 18630
    nodePort: 18635
    protocol: TCP
  selector:
    app: streamsets
  type: NodePort