namespace: jenkins-uat
resources:
  - ../../base
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_PROFILES_ACTIVE
          value: uat
    target:
      kind: Deployment
      name: jenkins
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: jenkins/jenkins
  newTag: test