apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-query-ui
  name: data-query-ui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: data-query-ui
  type: ClusterIP