apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cas-server-uat
  namespace: argocd
spec:
  destination:
    namespace: common-uat
    server: https://kubernetes.default.svc
  project: common
  source:
    path: common/cas-server/overlays/uat
    repoURL: https://github.com/wgzhao/k8s-deployment.git
    targetRevision: HEAD
  syncPolicy: {}