apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cas-server
  name: cas-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cas-server
  template:
    metadata:
      labels:
        app: cas-server
        logging: 'true'
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - image: common/cas-server:test
        name: cas-server
        imagePullPolicy: Always
        ports:
        - name: service-port
          containerPort: 8080
        startupProbe:
          tcpSocket:
            port: service-port
          failureThreshold: 20
          periodSeconds: 5
          initialDelaySeconds: 20
        readinessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: service-port
          initialDelaySeconds: 15
          periodSeconds: 3
        resources:
          requests:
            cpu: "100m"
            memory: "2048Mi"
          limits:
            memory: "8192Mi"
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:+UnlockExperimentalVMOptions -Xms64M -Duser.timezone=Asia/Chongqing -XX:MaxRAMPercentage=90"
          - name: TZ
            value: Asia/Chongqing
