apiVersion: v1
kind: Service
metadata:
  labels:
    app: cas-server
  name: cas-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: cas-server
  type: ClusterIP