apiVersion: v1
kind: Namespace
metadata:
   name: jenkins
   labels:
     name: jenkins
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: jenkins
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: jenkins
  destinations:
  - name: '*'
    namespace: jenkins
    server: '*'
  sourceRepos:
  - '*'
status: {}