apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager-flask
  namespace: argocd
spec:
  destination:
    namespace: grp-arch
    server: https://kubernetes.default.svc
  project: grp-arch
  source:
    path: grp-arch/alertmanager-flask/overlays/test
    repoURL: https://github.com/wgzhao/k8s-deployment.git
    targetRevision: HEAD
  syncPolicy: {}