apiVersion: v1
kind: Service
metadata:
  labels:
    app: alertmanager-flask
  name: alertmanager-flask
spec:
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 5000
    protocol: TCP
  selector:
    app: alertmanager-flask
  type: NodePort