apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: ${ns}
  labels:
    app: mysql
data:
  server.cnf: |
    # Apply this config only on the master.
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci 
    innodb_buffer_pool_size = 4096M
    innodb_data_file_path = ibdata1:100M:autoextend
    innodb_file_per_table = 1
    innodb_flush_log_at_trx_commit = 2
    innodb_temp_data_file_path=ibtmp1:20M:autoextend:max:500M
    innodb_change_buffering=all
    max_allowed_packet=1024M
    default-storage-engine = InnoDB
    sort_buffer_size = 16M
    server-id        = ${port}
    log-bin          = mysql-bin
    binlog_format    = row
    lower_case_table_names  = 1
    max_connections = 2000
    max_connect_errors = 500000
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    sync_binlog = 100
    innodb_buffer_pool_instances=4
    innodb_redo_log_capacity = 536870912
    innodb_io_capacity=1000
    innodb_thread_concurrency=16
    innodb_read_io_threads=8
    innodb_write_io_threads=8
    innodb_flush_method=O_DIRECT
    innodb_adaptive_flushing=1
    innodb_doublewrite  = 0
    key_buffer_size=64M
    back_log=1024
    binlog_expire_logs_seconds = 86400
    relay-log=mysql-0-relay-bin
    net_buffer_shrink_interval = 30
    # tuning thread pool size
    thread_handling=pool-of-threads
    thread_pool_size = 16
    innodb_empty_free_list_algorithm = backoff
    # for docker
    host_cache_size = 0
    skip-name-resolve
    [mysqld_safe]
    open-files-limit = 8192
    # enable validate password and audit plugin
    plugin-load-add=validate_password.so
    plugin-load-add=audit_log.so
    # password policy
    validate-password=FORCE_PLUS_PERMANENT
    validate_password_length=12
    validate_password_policy=STRONG
    # audit 
    audit_log_policy = ALL
    audit_log_strategy = ASYNCHRONOUS
    audit_log_rotate_on_size = 100M
    audit_log_rotations = 30
    audit_log_buffer_size = 1048576
    audit_log_format = CSV
    audit_log_exclude_commands = 'select,show_databases,show_tables,show_keys,show_fields,show_status,commit'
    # performance tuning
    ## enable numa
    innodb_numa_interleave = 1
    ## thread pool
    thread_handling=pool-of-threads
    ## improvement for high concurrency I/O-bound
    innodb_empty_free_list_algorithm=backoff
    innodb_flush_method = O_DIRECT
    skip-name-resolve
    expire_logs_days = 5
---