apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: ${ns}
  labels:
    app: mysql
data:
  server.cnf: |
    # Apply this config only on the master.
    [mysqld] 
    character-set-server=utf8mb4
    collation-server=utf8mb4_general_ci 
    innodb_buffer_pool_size = 4096M
    innodb_data_file_path = ibdata1:100M:autoextend
    innodb_file_per_table = 1
    innodb_flush_log_at_trx_commit = 0
    innodb_temp_data_file_path=ibtmp1:20M:autoextend:max:500M
    innodb_change_buffering=all
    max_allowed_packet=1024M
    default-storage-engine = InnoDB
    sort_buffer_size = 16M
    server-id        = 12
    log-bin          = mysql-bin
    binlog_format    = row
    lower_case_table_names  = 1
    max_connections = 2000
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    [mysqld_safe]
    open-files-limit = 8192
---