patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SPRING_PROFILES_ACTIVE
          value: ${profile}
    target:
      kind: Deployment
      name: ${project}
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: nexus.gp51.com/${ns}/${app}
  newTag: test