apiVersion: v1
kind: Namespace
metadata:
   name: ${project}
   labels:
     name: ${project}
---
apiVersion: v1
kind: Namespace
metadata:
   name: ${project}-test
   labels:
     name: ${project}-test
---
apiVersion: v1
kind: Namespace
metadata:
   name: ${project}-test
   labels:
     name: ${project}-test
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ${project}
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: ${project}
  destinations:
  - name: '*'
    namespace: ${ns}
    server: '*'
  - name: '*'
    namespace: ${ns}-test
    server: '*'
  - name: '*'
    namespace: ${ns}-uat
    server: '*'
  sourceRepos:
  - '*'
status: {}