apiVersion: v1
kind: Namespace
metadata:
   name: minio
   labels:
     name: minio
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: minio
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: minio
  destinations:
  - name: '*'
    namespace: minio
    server: '*'
  sourceRepos:
  - '*'
status: {}