apiVersion: v1
kind: Service
metadata:
  name: es-cluster
spec:
  selector:
    app: es #has to match .spec.template.metadata.labels
  ports:
  - name: transport
    port: 9300
  - name: rest
    port: 9200
    targetPort: 9200
  clusterIP: None # headless
  type: ClusterIP
